import { 
  Profile, 
  Skill, 
  Experience, 
  Project, 
  Education, 
  Certificate, 
  Achievement, 
  CareerEvidence,
  GitHubRepository,
  Job,
  JobRequirement
} from '@/lib/types/database';

export const DEMO_USER_ID = '00000000-0000-0000-0000-000000000001';

export const INITIAL_DEMO_PROFILE: Profile = {
  id: 'prof-001',
  user_id: DEMO_USER_ID,
  full_name: 'Yash Satish Sanikop',
  headline: 'Computer Engineering Undergraduate | Full-Stack, Distributed Systems & AI/ML',
  email: 'konuriyash@gmail.com',
  phone: '+91 8177963886',
  location: 'Goa, India',
  linkedin_url: 'https://linkedin.com/in/yashsanikop',
  github_url: 'https://github.com/ByteLounge',
  portfolio_url: 'https://yashsanikop.netlify.app',
  summary: 'Computer Engineering undergraduate who builds and ships complete systems, not prototypes — REST APIs in Flask/FastAPI, PostgreSQL-backed data models, Dockerized deployments, and applied NLP/ML pipelines. Comfortable working across the stack, with a track record of open-sourcing production-shaped projects and driving them from architecture through deployment.',
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_DEMO_SKILLS: Skill[] = [
  { id: 'sk-1', user_id: DEMO_USER_ID, name: 'Python', category: 'language', proficiency: 'advanced', years_of_experience: 3, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-2', user_id: DEMO_USER_ID, name: 'TypeScript', category: 'language', proficiency: 'advanced', years_of_experience: 2.5, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-3', user_id: DEMO_USER_ID, name: 'JavaScript', category: 'language', proficiency: 'advanced', years_of_experience: 3, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-4', user_id: DEMO_USER_ID, name: 'C / C++', category: 'language', proficiency: 'intermediate', years_of_experience: 2, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-5', user_id: DEMO_USER_ID, name: 'FastAPI', category: 'framework', proficiency: 'advanced', years_of_experience: 2, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-6', user_id: DEMO_USER_ID, name: 'Flask', category: 'framework', proficiency: 'advanced', years_of_experience: 2, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-7', user_id: DEMO_USER_ID, name: 'React', category: 'framework', proficiency: 'advanced', years_of_experience: 2.5, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-8', user_id: DEMO_USER_ID, name: 'Next.js', category: 'framework', proficiency: 'advanced', years_of_experience: 2, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-9', user_id: DEMO_USER_ID, name: 'PostgreSQL', category: 'database', proficiency: 'advanced', years_of_experience: 2, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-10', user_id: DEMO_USER_ID, name: 'Docker', category: 'tool', proficiency: 'advanced', years_of_experience: 2, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-11', user_id: DEMO_USER_ID, name: 'PyTorch & Transformers', category: 'ai_ml', proficiency: 'advanced', years_of_experience: 2, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'sk-12', user_id: DEMO_USER_ID, name: 'RAG & Vector Search', category: 'ai_ml', proficiency: 'advanced', years_of_experience: 1.5, verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

export const INITIAL_DEMO_EXPERIENCE: Experience[] = [
  {
    id: 'exp-1',
    user_id: DEMO_USER_ID,
    company: 'Lenovo India',
    role: 'Artificial Intelligence Intern',
    employment_type: 'internship',
    location: 'Remote',
    start_date: '2025-07-01',
    end_date: '2025-08-31',
    is_current: false,
    responsibilities: [
      'Engineered NLP-based conversational chatbots in Botpress across an 8-week internship, designing multi-turn dialogue flows for domain-specific use cases',
      'Prototyped a contextual conversational-AI flow and iterated on prompt design through repeated testing cycles to improve response relevance and reduce dead-end conversations',
    ],
    achievements: [
      'Successfully deployed enterprise conversational flows with measurable reduction in fallback dead-ends',
    ],
    technologies: ['NLP', 'Botpress', 'Prompt Engineering', 'Python', 'Conversational AI'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'exp-2',
    user_id: DEMO_USER_ID,
    company: 'CareMeez',
    role: 'Backend & Mobile App Intern',
    employment_type: 'internship',
    location: 'Remote',
    start_date: '2025-10-01',
    end_date: '2026-01-31',
    is_current: false,
    responsibilities: [
      'Implemented backend database operations supporting video processing and structured data storage in production Firebase collections',
      'Debugged and optimized mobile app UI components, improving responsiveness and reducing reported performance issues',
    ],
    achievements: [
      'Streamlined video metadata indexing pipelines and optimized Firestore queries',
    ],
    technologies: ['Firebase', 'React Native', 'Mobile Development', 'TypeScript', 'NoSQL'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'exp-3',
    user_id: DEMO_USER_ID,
    company: 'RoboClub — Agnel Institute of Technology and Design',
    role: 'President',
    employment_type: 'contract',
    location: 'Goa, India',
    start_date: '2024-07-01',
    end_date: null,
    is_current: true,
    responsibilities: [
      "Led the launch of RoboClub's official website, serving as the primary information and event-registration hub for 300+ students",
      'Organized technical workshops and inter-college competitions for 100+ participants, managing logistics, sponsor coordination, and volunteer teams',
    ],
    achievements: [
      'Scaled club event registrations to 300+ active students across Goa technical colleges',
    ],
    technologies: ['Leadership', 'Full-Stack Development', 'React', 'Event Coordination'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    user_id: DEMO_USER_ID,
    title: 'BotifyNow — AI Chat & RAG Platform',
    description: 'Context-aware conversational RAG application extracting and answering queries across technical PDFs using vector similarity.',
    role: 'Lead Architect',
    technologies: ['Python', 'FastAPI', 'OpenAI API', 'Qdrant', 'React', 'Vite'],
    github_url: 'https://github.com/ByteLounge/BotifyNow-AI-Chat-RAG-APIs',
    deployment_url: null,
    architecture_overview: 'Decoupled FastAPI microservices with Qdrant vector indexing and interactive React client.',
    highlights: [
      'Architected a RAG pipeline combining OpenAI embeddings with Qdrant vector search to deliver context-aware answers over user-uploaded PDF/text documents',
      'Decoupled the backend into independent service modules (embedding, retrieval, generation, PDF extraction) behind a FastAPI REST layer',
      'Built a React + Vite chat interface with live typing indicators and automatic document summarization on upload',
    ],
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-2',
    user_id: DEMO_USER_ID,
    title: 'Inventory Management System — Full-Stack SaaS',
    description: 'High-throughput inventory tracking and auditing REST platform built with Flask, PostgreSQL, and Docker.',
    role: 'Backend & Systems Architect',
    technologies: ['React', 'TypeScript', 'Flask', 'PostgreSQL', 'Docker', 'JWT', 'Alembic'],
    github_url: 'https://github.com/ByteLounge/Inventory-Management-System',
    deployment_url: null,
    architecture_overview: 'Flask REST API with SQLAlchemy ORM, Alembic migrations, PostgreSQL 15, and Docker Compose orchestration.',
    highlights: [
      'Designed a Flask REST API with SQLAlchemy ORM and Alembic migrations, backed by PostgreSQL 15, to manage inventory, sales, and stock-alert data',
      'Secured endpoints with JWT authentication and bcrypt password hashing; served via Gunicorn for production readiness',
      'Containerized frontend, backend, and database with Docker Compose for single-command orchestration and dev/prod parity',
    ],
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-3',
    user_id: DEMO_USER_ID,
    title: 'Persona-Ranking — Offline NLP Document Intelligence',
    description: 'Offline NLP document intelligence engine ranking persona-relevant sections across PDF batches using sentence transformers.',
    role: 'ML Engineer',
    technologies: ['Python', 'sentence-transformers', 'PyTorch', 'scikit-learn', 'Docker'],
    github_url: 'https://github.com/ByteLounge/Persona-Ranking',
    deployment_url: null,
    architecture_overview: 'Network-isolated Docker container running offline transformer inference over batched PDF corpora.',
    highlights: [
      'Built an NLP pipeline that ranks and extracts persona-relevant sections from batches of PDFs using sentence-transformer embeddings',
      'Packaged the full inference stack into a network-isolated Docker image (--network none), enabling secure, fully offline batch processing',
      'Automated matching of each job configuration to its referenced source PDFs, processing multiple jobs sequentially without manual intervention',
    ],
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-4',
    user_id: DEMO_USER_ID,
    title: 'Network Intrusion Detection System',
    description: 'End-to-end machine learning packet classification and live intrusion detection system.',
    role: 'Security & ML Developer',
    technologies: ['Python', 'scikit-learn', 'pandas', 'tshark', 'Tkinter'],
    github_url: 'https://github.com/ByteLounge/Network-Intrusion-Detection-System',
    deployment_url: null,
    architecture_overview: 'Packet capture stream processed through feature engineering pipeline into Random Forest classifier.',
    highlights: [
      'Built an end-to-end ML pipeline — packet capture → feature extraction → training → detection — using a Random Forest classifier on the NSL-KDD dataset',
      'Implemented a CLI and Tkinter GUI exposing capture, preprocessing, training, evaluation, and live-detection as independently runnable commands',
      'Automated evaluation reporting (classification reports, confusion matrices) and persistent alert logging for detected intrusions',
    ],
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-5',
    user_id: DEMO_USER_ID,
    title: 'sar-crop-intelligence',
    description: 'Multi-temporal X-band SAR pipeline for crop mapping and cultivated area estimation.',
    role: 'ML & Geospatial Engineer',
    technologies: ['Python', 'Machine Learning', 'Geospatial', 'Feature Engineering'],
    github_url: 'https://github.com/ByteLounge/sar-crop-intelligence',
    deployment_url: null,
    architecture_overview: 'Geospatial satellite preprocessing pipeline with machine learning segmentation.',
    highlights: [
      'Multi-temporal X-band SAR pipeline for crop mapping and cultivated area estimation using machine learning, feature engineering, and geospatial preprocessing',
    ],
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_DEMO_EDUCATION: Education[] = [
  {
    id: 'edu-1',
    user_id: DEMO_USER_ID,
    institution: 'Agnel Institute of Technology and Design, Goa',
    degree: 'B.E. Computer Engineering',
    field_of_study: 'Computer Engineering',
    start_date: '2023-07-01',
    end_date: '2027-06-30',
    is_current: true,
    gpa: '7.74 / 10',
    coursework: [
      'Data Structures & Algorithms',
      'Operating Systems',
      'Database Management Systems',
      'Machine Learning',
      'Computer Networks',
      'Software Engineering'
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_DEMO_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-1',
    user_id: DEMO_USER_ID,
    name: 'Python & React (NPTEL)',
    issuer: 'NPTEL / IIT',
    issue_date: '2024-05-10',
    skills_covered: ['Python', 'React', 'Web Development'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cert-2',
    user_id: DEMO_USER_ID,
    name: 'Google Digital Marketing',
    issuer: 'Google',
    issue_date: '2024-08-15',
    skills_covered: ['Digital Marketing', 'Analytics'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cert-3',
    user_id: DEMO_USER_ID,
    name: 'Meta AR — Creators of the Metaverse',
    issuer: 'Meta',
    issue_date: '2024-11-20',
    skills_covered: ['Augmented Reality', 'Meta Spark'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_DEMO_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    user_id: DEMO_USER_ID,
    title: 'President, RoboClub',
    organization: 'Agnel Institute of Technology and Design',
    date: '2024-07-01',
    ranking: 'Executive Head',
    description: 'Leading RoboClub official technical events, website launch, and workshops for 300+ students.',
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_DEMO_EVIDENCE: CareerEvidence[] = [
  {
    id: 'ev-1',
    user_id: DEMO_USER_ID,
    type: 'project',
    title: 'BotifyNow RAG Architecture',
    claim: 'Architected RAG pipeline combining OpenAI embeddings with Qdrant vector search for context-aware document QA.',
    skills: ['Python', 'FastAPI', 'Qdrant', 'RAG & Vector Search'],
    source_type: 'github',
    source_id: 'proj-1',
    source_reference: 'github.com/ByteLounge/BotifyNow-AI-Chat-RAG-APIs',
    confidence: 1.0,
    verification_status: 'VERIFIED',
    verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ev-2',
    user_id: DEMO_USER_ID,
    type: 'github_code',
    title: 'Inventory SaaS Dockerization & ORM',
    claim: 'Designed Flask REST API with PostgreSQL 15, Alembic migrations, and Docker Compose orchestration.',
    skills: ['Docker', 'PostgreSQL', 'Flask', 'SQLAlchemy'],
    source_type: 'github',
    source_id: 'proj-2',
    source_reference: 'github.com/ByteLounge/Inventory-Management-System (docker-compose.yml, app.py)',
    confidence: 1.0,
    verification_status: 'VERIFIED',
    verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ev-3',
    user_id: DEMO_USER_ID,
    type: 'project',
    title: 'Persona-Ranking NLP Pipeline',
    claim: 'Built offline NLP pipeline using sentence-transformers packaged in network-isolated Docker images.',
    skills: ['Python', 'PyTorch & Transformers', 'Docker', 'NLP'],
    source_type: 'github',
    source_id: 'proj-3',
    source_reference: 'github.com/ByteLounge/Persona-Ranking',
    confidence: 1.0,
    verification_status: 'VERIFIED',
    verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ev-4',
    user_id: DEMO_USER_ID,
    type: 'professional_experience',
    title: 'Lenovo India AI Internship',
    claim: 'Engineered NLP conversational chatbots in Botpress and designed multi-turn dialogue flows.',
    skills: ['NLP', 'Botpress', 'Prompt Engineering', 'Python'],
    source_type: 'profile',
    source_id: 'exp-1',
    source_reference: 'Lenovo India Artificial Intelligence Internship',
    confidence: 1.0,
    verification_status: 'VERIFIED',
    verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ev-5',
    user_id: DEMO_USER_ID,
    type: 'professional_experience',
    title: 'CareMeez Backend & Mobile Engineering',
    claim: 'Implemented backend database operations in production Firebase and optimized mobile app components.',
    skills: ['Firebase', 'React Native', 'TypeScript'],
    source_type: 'profile',
    source_id: 'exp-2',
    source_reference: 'CareMeez Backend & Mobile App Internship',
    confidence: 1.0,
    verification_status: 'VERIFIED',
    verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ev-6',
    user_id: DEMO_USER_ID,
    type: 'certificate',
    title: 'AWS Certified Cloud Practitioner',
    claim: 'Certified foundational cloud concepts, IAM security, and core AWS compute/storage architecture.',
    skills: ['AWS S3', 'Cloud Architecture'],
    source_type: 'document',
    source_id: 'cert-1',
    source_reference: 'Credential AWS-CCP-9821381',
    confidence: 1.0,
    verification_status: 'VERIFIED',
    verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_DEMO_REPOS: GitHubRepository[] = [
  {
    id: 'repo-1',
    user_id: DEMO_USER_ID,
    repo_name: 'inventory-api',
    repo_full_name: 'alexmorgan-dev/inventory-api',
    html_url: 'https://github.com/alexmorgan-dev/inventory-api',
    description: 'High-performance inventory auditing REST microservice',
    primary_language: 'Python',
    detected_skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'JWT', 'REST APIs'],
    demonstrated_features: ['REST API endpoints', 'Relational database models', 'Dockerfile container configuration'],
    selected_for_analysis: true,
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'repo-2',
    user_id: DEMO_USER_ID,
    repo_name: 'taskflow',
    repo_full_name: 'alexmorgan-dev/taskflow',
    html_url: 'https://github.com/alexmorgan-dev/taskflow',
    description: 'Real-time collaborative task management system',
    primary_language: 'TypeScript',
    detected_skills: ['TypeScript', 'React', 'Next.js', 'Tailwind CSS', 'PostgreSQL'],
    demonstrated_features: ['Full-stack App Router', 'Optimistic UI', 'Component architecture'],
    selected_for_analysis: true,
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'repo-3',
    user_id: DEMO_USER_ID,
    repo_name: 'rag-assistant',
    repo_full_name: 'alexmorgan-dev/rag-assistant',
    html_url: 'https://github.com/alexmorgan-dev/rag-assistant',
    description: 'Document intelligence assistant with grounded citations',
    primary_language: 'Python',
    detected_skills: ['Python', 'FastAPI', 'Vector Embeddings', 'React'],
    demonstrated_features: ['Chunking pipeline', 'Semantic retrieval', 'Citations verification'],
    selected_for_analysis: true,
    last_analyzed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_DEMO_JOBS: Job[] = [
  {
    id: 'job-1',
    user_id: DEMO_USER_ID,
    company: 'Stripe',
    role: 'Software Engineer Intern — Core Infrastructure',
    job_url: 'https://stripe.com/jobs/swe-intern',
    job_description: `About the Role:
We are looking for a Software Engineer Intern to join our Core Infrastructure team. In this role, you will build and scale reliable backend services and APIs handling millions of daily requests.

Requirements:
- Strong proficiency in Python, TypeScript, Go, or Java
- Solid understanding of REST APIs, relational databases (PostgreSQL or MySQL)
- Familiarity with containerization technologies like Docker
- Hands-on experience building full-stack web applications or microservices
- Dedication to clean architecture, automated testing, and code quality

Nice to have:
- Experience with Redis caching or distributed systems
- Cloud platforms (AWS, GCP)
- Familiarity with Next.js or React for developer tooling portals`,
    description_hash: 'hash-stripe-swe-intern-001',
    status: 'Analyzed',
    deadline: '2026-10-31',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_DEMO_JOB_REQUIREMENTS: JobRequirement[] = [
  { id: 'req-1', job_id: 'job-1', user_id: DEMO_USER_ID, requirement: 'Proficiency in Python or TypeScript', category: 'REQUIRED', keywords: ['Python', 'TypeScript'], weight: 1.0, created_at: new Date().toISOString() },
  { id: 'req-2', job_id: 'job-1', user_id: DEMO_USER_ID, requirement: 'REST API design and development', category: 'REQUIRED', keywords: ['REST APIs', 'FastAPI'], weight: 1.0, created_at: new Date().toISOString() },
  { id: 'req-3', job_id: 'job-1', user_id: DEMO_USER_ID, requirement: 'Relational databases (PostgreSQL)', category: 'REQUIRED', keywords: ['PostgreSQL', 'SQL'], weight: 1.0, created_at: new Date().toISOString() },
  { id: 'req-4', job_id: 'job-1', user_id: DEMO_USER_ID, requirement: 'Containerization using Docker', category: 'REQUIRED', keywords: ['Docker', 'Containers'], weight: 0.9, created_at: new Date().toISOString() },
  { id: 'req-5', job_id: 'job-1', user_id: DEMO_USER_ID, requirement: 'Automated testing and code quality', category: 'RESPONSIBILITY', keywords: ['Testing', 'Code Review'], weight: 0.8, created_at: new Date().toISOString() },
  { id: 'req-6', job_id: 'job-1', user_id: DEMO_USER_ID, requirement: 'Redis caching experience', category: 'PREFERRED', keywords: ['Redis', 'Caching'], weight: 0.7, created_at: new Date().toISOString() },
  { id: 'req-7', job_id: 'job-1', user_id: DEMO_USER_ID, requirement: 'Kubernetes production orchestration', category: 'PREFERRED', keywords: ['Kubernetes', 'K8s'], weight: 0.6, created_at: new Date().toISOString() },
];
